- name: SAP Faplocy - Service fapolicy state - enable
  ansible.builtin.command: "systemctl enable fapolicyd"

- name: SAP Faplocy - Service fapolicy state - start
  ansible.builtin.command: "systemctl start fapolicyd"