- name: SAP Fapolicy - Gathering Package Facts
  package_facts:
    manager: auto

- name: SAP Fapolicy - Setup
  block:    

    - name: Get sidadm user of SID
      include_tasks: get_sidadm_user.yml
      when:
        - "'generic' not in sap_fapolicy_type"
        - sap_fapolicy_user is defined

    # # At this point, we should have all sidadm user + the default users
    # - debug:
    #     msg:
    #       - "{{ sap_fapolicy_user_list }}"
    
    # Get UIDs of users
    # List is stored in sap_fapolicy_uid_list
    - name: Get UID of user
      vars:
        passed_user: "{{ sap_fapolicy_user | lower }}"
      include_tasks: get_user_uid.yml

    # # At this point, we should have all uids
    # - debug:
    #     msg:
    #       - "{{ sap_fapolicy_uid_list }}"

    - name: SAP Fapolicy - Enable Fapolicy
      include_tasks: "enable_fapolicy.yml"

    - name: SAP Fapolicy - Update Fapolicy
      include_tasks: "update_fapolicy.yml"

  when: 
    - ansible_virtualization_role != "guest" or ansible_virtualization_type != "docker"
    - '"fapolicyd" in ansible_facts.packages'

