- name: SAP {{ sap_control_name_header }} - Cleanipc {{ passed_sap_nr }}
  shell: |
    source ~/.profile && cleanipc {{ passed_sap_nr }} remove
  args:
    executable: /bin/bash
  become: yes
  become_method: sudo
  become_user: "{{ passed_sap_sid | lower }}adm"
  register: cleanipc
  changed_when:
    - "'Number of IPC-Objects...........:    0' not in cleanipc.stdout"